version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: vtb_postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5433:5432"
    # Включаем статистику (обязательно для алгоритма)
    command: postgres -c shared_preload_libraries=pg_stat_statements -c pg_stat_statements.track=all
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      # Монтируем файл профилей, чтобы он выполнился при создании базы
      - ./profiles.sql:/docker-entrypoint-initdb.d/init_profiles.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d mydb"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: