version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: vtb_postgres
    restart: always
    environment:
      POSTGRES_DB: tpc_tests
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts:/scripts
      - ./workloads:/workloads
      - ./profiles.sql:/docker-entrypoint-initdb.d/init_profiles.sql
    command: >
      postgres
      -c shared_preload_libraries=pg_stat_statements
      -c pg_stat_statements.track=all
      -c pg_stat_statements.max=10000

  metrics-collector:
    build:
      context: .
      dockerfile: Dockerfile.metrics
    depends_on:
      - db
    volumes:
      - ./scripts:/scripts
      - ./results:/results
      - ./workloads:/workloads
    working_dir: /scripts
volumes:
  postgres_data:
